apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://github.com/birlinn/dpk8s.git
    targetRevision: 1.10.3
